name: Go CI/CD Completo

on: [push, pull_request]

jobs:
  qualidade-e-testes:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: root
          POSTGRES_DB: root
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout do c칩digo
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Instalar Golangci-lint
        run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.55.2

      - name: Rodar Minha Ferramenta de Qualidade
        env:
          HOST: localhost
          USER: ${{ secrets.DB_USER }}
          PASSWORD: ${{ secrets.DB_PASSWORD }}  # <-- AGORA SIM, PROFISSIONAL
          DBNAME: root
          PORT: 5432
        run: |
          chmod +x ./quality-check.sh
          ./quality-check.sh

  build:
    needs: qualidade-e-testes
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Checkout do c칩digo
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      
      - name: Compilando o Bin치rio
        # Aqui removemos o passo de "go test" que estava dando erro!
        run: |
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            go build -o main.exe
          else
            go build -o main-${{ matrix.os }}
          fi
        shell: bash

      - name: Upload do Execut치vel
        uses: actions/upload-artifact@v4
        with:
          name: executavel-${{ matrix.os }}
          path: main*